#!/usr/bin/env bash                                                                              set -e                                                                                           echo "Running demo: starts mock Mina verifier and relayer (they auto-run)."                      echo "Open the frontend at frontend_demo/index.html in a browser to view mock data."             echo "Steps:"                                                                                    echo "1) Start Mina mock verifier: (in one terminal)"        
echo "   cd mina && npm install && npm start"
echo "2) Start relayer: (in another terminal)"
echo "   cd relayer && npm install && npm start"
echo ""
echo "Relayer will emit a mock deposit every 5s, call the circom generator to write a toy proof,"
echo "and submit the proof to the Mina mock verifier at http://localhost:5001/mina/submit."      
echo ""
echo "To run both in background from this script (test convenience), uncomment the lines below." 
# (cd mina && npm install --silent && npm start &) 
